# Generated by Django 4.0.2 on 2022-04-13 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['date_created']},
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='transaction_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
